export const SHUFFLE_DECK = "SHUFFLE_DECK";
export const ADD_DECK = "ADD_DECK";
export const INCREMENT_STEP = "INCREMENT_STEP";
export const INCREMENT_DEALER_SCORE = "INCREMENT_DEALER_SCORE";
export const INCREMENT_PLAYER_SCORE = "INCREMENT_PLAYER_SCORE";
